name: C++ Modules CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows-msvc:
    name: Windows (MSVC + Qt6 + C++20 Modules)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install aqtinstall
        run: |
          python -m pip install --upgrade pip
          pip install aqtinstall

      - name: Install Qt 6.10.0
        run: |
          aqt install-qt windows desktop 6.8.0 win64_msvc2022_64 -O $env:GITHUB_WORKSPACE\Qt --archives qtbase qtdeclarative
        shell: powershell

      - name: Install CMake 4.x
        run: |
          choco install cmake --version=4.1.2 --installargs 'ADD_CMAKE_TO_PATH=System'
        shell: powershell

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -DCMAKE_PREFIX_PATH="$env:GITHUB_WORKSPACE\Qt\6.8.0\msvc2022_64"

      - name: Build
        run: cmake --build build --config Release